"use client";

import { ReactNode } from 'react';
import { ArrowLeft, Share2, Download } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';

interface UniformLayoutProps {
  title: string;
  subtitle?: string;
  location?: string;
  children: ReactNode;
  tabs?: Array<{
    id: string;
    label: string;
    icon: ReactNode;
    active?: boolean;
    onClick: () => void;
  }>;
  actions?: ReactNode;
}

export default function UniformLayout({ 
  title, 
  subtitle, 
  location, 
  children, 
  tabs, 
  actions 
}: UniformLayoutProps) {
  const router = useRouter();

  const handleShare = async () => {
    const shareData = {
      title: title,
      text: subtitle || `Business analysis for ${title}`,
      url: window.location.href
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard!');
      }
    } catch (error) {
      console.error('Error sharing:', error);
      // Fallback: copy to clipboard
      try {
        await navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard!');
      } catch (clipboardError) {
        console.error('Clipboard error:', clipboardError);
      }
    }
  };

  const handleDownload = () => {
    // Create a simple text report
    const reportContent = `
Business Analysis Report
========================

Title: ${title}
${subtitle ? `Subtitle: ${subtitle}` : ''}
${location ? `Location: ${location}` : ''}
Generated: ${new Date().toLocaleDateString()}
URL: ${window.location.href}

This report was generated by your business analysis platform.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#020617] transition-colors duration-500">
      {/* Header */}
      <div className="fixed top-20 sm:top-[160px] lg:top-[180px] left-0 right-0 z-40 bg-white dark:bg-[#0a0f25] border-b border-slate-200 dark:border-white/5 shadow-sm">
        <div className="responsive-container py-4 sm:py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <button
                onClick={() => router.push('/dashboard')}
                className="flex items-center space-x-2 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
              >
                <ArrowLeft className="w-5 h-5" />
                <span className="font-medium">Back to Dashboard</span>
              </button>
              <div className="h-6 w-px bg-slate-200 dark:bg-white/10" />
              <div>
                <h1 className="text-xl sm:text-2xl lg:text-3xl font-black text-slate-900 dark:text-white tracking-tight">
                  {title}
                </h1>
                {subtitle && (
                  <p className="text-sm sm:text-base text-slate-500 dark:text-gray-400 mt-1">
                    {subtitle}
                  </p>
                )}
                {location && (
                  <p className="text-xs sm:text-sm text-emerald-600 dark:text-emerald-400 font-medium mt-1 flex items-center">
                    <span className="w-2 h-2 bg-emerald-500 rounded-full mr-2"></span>
                    {location}
                  </p>
                )}
              </div>
            </div>
            <div className="flex items-center space-x-2 sm:space-x-3">
              {actions}
              <button 
                onClick={handleShare}
                className="p-2 sm:p-2.5 bg-slate-100 dark:bg-white/5 hover:bg-slate-200 dark:hover:bg-white/10 rounded-lg text-slate-600 dark:text-gray-400 hover:text-slate-900 dark:hover:text-white transition-all border border-slate-200 dark:border-white/10"
                title="Share this page"
              >
                <Share2 className="w-4 h-4 sm:w-5 sm:h-5" />
              </button>
              <button 
                onClick={handleDownload}
                className="p-2 sm:p-2.5 bg-slate-100 dark:bg-white/5 hover:bg-slate-200 dark:hover:bg-white/10 rounded-lg text-slate-600 dark:text-gray-400 hover:text-slate-900 dark:hover:text-white transition-all border border-slate-200 dark:border-white/10"
                title="Download report"
              >
                <Download className="w-4 h-4 sm:w-5 sm:h-5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Navigation Tabs */}
      {tabs && (
        <div className="fixed top-40 sm:top-[220px] lg:top-[244px] left-0 right-0 z-30 bg-white dark:bg-[#0a0f25] border-b border-slate-200 dark:border-white/5">
          <div className="responsive-container">
            <div className="flex space-x-6 sm:space-x-8 overflow-x-auto scrollbar-hide">
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={tab.onClick}
                  className={`flex items-center space-x-2 py-3 sm:py-4 px-1 border-b-2 transition-all whitespace-nowrap ${
                    tab.active
                      ? 'border-emerald-500 text-emerald-600 dark:text-emerald-400'
                      : 'border-transparent text-slate-500 dark:text-gray-500 hover:text-slate-700 dark:hover:text-gray-300 hover:border-slate-300 dark:hover:border-white/20'
                  }`}
                >
                  <span className="flex-shrink-0">{tab.icon}</span>
                  <span className="font-medium text-sm sm:text-base">{tab.label}</span>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Content */}
      <div className={`responsive-container py-6 sm:py-8 ${tabs ? 'mt-60 sm:mt-[300px] lg:mt-[320px]' : 'mt-32 sm:mt-[240px] lg:mt-[260px]'}`}>
        {children}
      </div>
    </div>
  );
}