"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  English: {
    // Navbar
    nav_dashboard: "Terminal",
    nav_profile: "User Profile",
    nav_logout: "Terminate Session",
    nav_select_lang: "Select Intelligence Language",
    // Home Page
    hero_badge: "Advanced Neural Intelligence Protocol",
    hero_title_1: "Deploy Profitability in",
    hero_title_2: "Any Territory",
    hero_subtitle: "Utilizing real-time neural scans of global trends and community sentiment to architect high-growth business ventures.",
    btn_start_scan: "Initiate Market Scan",
    btn_pricing: "Acquisition Tiers",
    feat_title: "Strategic Intelligence Framework",
    feat_subtitle: "Aggregating multi-vector data points to synthesize actionable deployment blueprints.",
    feat_1_title: "Territorial Mapping",
    feat_1_desc: "Define your geographical target. Our systems map demographic density and localized digital footprints.",
    feat_2_title: "Sentiment Extraction",
    feat_2_desc: "Neural analysis of community networks to identify unvocalized market friction and demand.",
    feat_3_title: "Directive Synthesis",
    feat_3_desc: "Generated operational plans detailing capital allocation, risk assessment, and launch sequences.",
    banner_title: "Ready to Architect Your Venture?",
    banner_desc: "Join global entrepreneurs utilizing localized intelligence to mitigate market entry risks.",
    banner_btn: "Activate Terminal Access",
    // Dashboard
    dash_market_scope: "Geographical Perimeter",
    dash_target_loc: "Target Domain",
    dash_enter_city: "Specify city, district, or region...",
    dash_analyze: "Execute Neural Scan",
    dash_analyzing: "Decrypting Regional Signals...",
    dash_ai_insights: "Intelligence Vectors",
    dash_ai_desc: "Our neural architecture cross-references real-time community sentiment with global economic indicators.",
    dash_vector_global: "Real-time Vector Analysis",
    dash_vector_predict: "Predictive Economic Engine",
    dash_results_header: "Intelligence Report:",
    dash_strategic_opps: "Identified Strategic Opportunities",
    dash_view_plan: "Access Deployment Plan",
    dash_match_score: "Synergy Match",
    dash_revenue: "Projected Revenue",
    dash_capital: "Initial Capital",
    dash_prob: "Survival Probability",
    dash_neural_input: "Neural Source Verification",
    dash_source_web: "Global Trend Indicators (Google)",
    dash_source_reddit: "Community Sentiment (Reddit)",
    dash_empty_title: "Terminal Ready for Input",
    dash_empty_desc: "Awaiting territorial coordinates to initiate deep market intelligence sequence.",
    // Roadmap
    road_return: "Return to Terminal",
    road_directive: "Operational Directive",
    road_milestones: "Milestone Sequence",
    road_timeline: "Strategic Timeline",
    road_team: "Resource Allocation",
    road_phase: "PHASE",
    road_priority: "Mission Critical",
    road_action: "Required Protocol",
    road_readiness: "Readiness Confirmed",
    road_confirmed_desc: "The deployment blueprint has been optimized for the identified economic terrain. Execution is authorized.",
    road_print: "Generate Protocol Document",
    // Profile
    prof_header: "User Configuration",
    prof_email_label: "Authorized Email Account",
    prof_name: "Legal Full Name",
    prof_bio: "Professional Biography",
    prof_phone: "Tactical Contact Number",
    prof_save: "Synchronize Changes",
    prof_updated: "Configuration Synchronized Successfully",
    prof_placeholder_name: "Enter full name...",
    prof_placeholder_bio: "Describe your professional objectives...",
    prof_placeholder_phone: "Enter contact digits...",
    prof_loading: "Accessing Secure Profile...",
    // Pricing
    price_title: "Acquisition Tiers",
    price_subtitle: "Unlock full access to deep regional analytics, competitor tracking, and advanced AI insights.",
    price_starter: "Starter Protocol",
    price_starter_desc: "Perfect for individuals exploring casual ideas.",
    price_pro: "Elite Professional",
    price_pro_desc: "For serious entrepreneurs and agencies.",
    price_free: "Initiate Free Access",
    price_upgrade: "Upgrade to Elite",
    price_popular: "MOST OPTIMAL",
    price_searches: "Regional Searches",
    price_unlimited: "Unlimited Searches",
    price_google: "Basic Web Trends",
    price_adv_data: "Advanced Data Mapping",
    price_recs: "Intelligence Reports",
    price_sent: "Sentiment Analysis",
    price_comp: "Territorial Mapping",
    price_export: "Export Directives"
  },
  Hindi: {
    // Navbar
    nav_dashboard: "टर्मिनल",
    nav_profile: "उपयोगकर्ता प्रोफाइल",
    nav_logout: "सत्र समाप्त करें",
    nav_select_lang: "खुफिया भाषा चुनें",
    // Home Page
    hero_badge: "उन्नत तंत्रिका खुफिया प्रोटोकॉल",
    hero_title_1: "किसी भी क्षेत्र में",
    hero_title_2: "लाभप्रदता तैनात करें",
    hero_subtitle: "उच्च-वृद्धि वाले व्यावसायिक उद्यमों को तैयार करने के लिए वैश्विक रुझानों और सामुदायिक भावना के वास्तविक समय के तंत्रिका स्कैन का उपयोग करना।",
    btn_start_scan: "बाजार स्कैन शुरू करें",
    btn_pricing: "अधिग्रहण स्तर",
    feat_title: "रणनीतिक खुफिया ढांचा",
    feat_subtitle: "कार्रवाई योग्य तैनाती ब्लूप्रिंट को संश्लेषित करने के लिए मल्टी-वेक्टर डेटा पॉइंट्स को एकत्रित करना।",
    feat_1_title: "क्षेत्रीय मानचित्रण",
    feat_1_desc: "अपना भौगोलिक लक्ष्य निर्धारित करें। हमारी प्रणालियाँ जनसांख्यिकीय घनत्व और स्थानीयकृत डिजिटल पदचिह्नों का मानचित्रण करती हैं।",
    feat_2_title: "भावना निष्कर्षण",
    feat_2_desc: "अव्यक्त बाजार घर्षण और मांग की पहचान करने के लिए सामुदायिक नेटवर्क का तंत्रिका विश्लेषण।",
    feat_3_title: "निर्देश संश्लेषण",
    feat_3_desc: "पूंजी आवंटन, जोखिम मूल्यांकन और लॉन्च अनुक्रमों का विवरण देने वाली उत्पन्न परिचालन योजनाएं।",
    banner_title: "क्या आप अपने उद्यम को आकार देने के लिए तैयार हैं?",
    banner_desc: "बाजार प्रवेश जोखिमों को कम करने के लिए स्थानीय खुफिया जानकारी का उपयोग करने वाले वैश्विक उद्यमियों में शामिल हों।",
    banner_btn: "टर्मिनल एक्सेस सक्रिय करें",
    // Dashboard
    dash_market_scope: "भौगोलिक परिधि",
    dash_target_loc: "लक्ष्य क्षेत्र",
    dash_enter_city: "शहर, जिला या क्षेत्र निर्दिष्ट करें...",
    dash_analyze: "तंत्रिका स्कैन निष्पादित करें",
    dash_analyzing: "क्षेत्रीय संकेतों को डिकोड किया जा रहा है...",
    dash_ai_insights: "खुफिया वेक्टर",
    dash_ai_desc: "हमारी तंत्रिका वास्तुकला वैश्विक आर्थिक संकेतकों के साथ वास्तविक समय की सामुदायिक भावना को क्रॉस-रेफरेंस करती है।",
    dash_vector_global: "वास्तविक समय वेक्टर विश्लेषण",
    dash_vector_predict: "भविष्य कहनेवाला आर्थिक इंजन",
    dash_results_header: "खुफिया रिपोर्ट:",
    dash_strategic_opps: "पहचाने गए रणनीतिक अवसर",
    dash_view_plan: "तैनाती योजना देखें",
    dash_match_score: "तालमेल मिलान",
    dash_revenue: "अनुमानित राजस्व",
    dash_capital: "प्रारंभिक पूंजी",
    dash_prob: "जीविता की संभावना",
    dash_neural_input: "तंत्रिका स्रोत सत्यापन",
    dash_source_web: "वैश्विक रुझान संकेतक (Google)",
    dash_source_reddit: "सामुदायिक भावना (Reddit)",
    dash_empty_title: "इनपुट के लिए टर्मिनल तैयार",
    dash_empty_desc: "गहन बाजार खुफिया अनुक्रम शुरू करने के लिए क्षेत्रीय निर्देशांक की प्रतीक्षा है।",
    // Roadmap
    road_return: "टर्मिनल पर लौटें",
    road_directive: "परिचालन निर्देश",
    road_milestones: "पड़ाव अनुक्रम",
    road_timeline: "रणनीतिक समयरेखा",
    road_team: "संसाधन आवंटन",
    road_phase: "चरण",
    road_priority: "मिशन के लिए महत्वपूर्ण",
    road_action: "आवश्यक प्रोटोकॉल",
    road_readiness: "तत्परता की पुष्टि की गई",
    road_confirmed_desc: "तैनाती ब्लूप्रिंट को पहचाने गए आर्थिक क्षेत्र के लिए अनुकूलित किया गया है। निष्पादन अधिकृत है।",
    road_print: "प्रोटोकॉल दस्तावेज़ तैयार करें",
    // Profile
    prof_header: "उपयोगकर्ता कॉन्फ़िगरेशन",
    prof_email_label: "अधिकृत ईमेल खाता",
    prof_name: "कानूनी पूरा नाम",
    prof_bio: "पेशेवर जीवनी",
    prof_phone: "रणनीतिक संपर्क नंबर",
    prof_save: "परिवर्तन सिंक्रनाइज़ करें",
    prof_updated: "कॉन्फ़िगरेशन सफलतापूर्वक सिंक्रनाइज़ किया गया",
    prof_placeholder_name: "पूरा नाम दर्ज करें...",
    prof_placeholder_bio: "अपने पेशेवर उद्देश्यों का वर्णन करें...",
    prof_placeholder_phone: "संपर्क नंबर दर्ज करें...",
    prof_loading: "सुरक्षित प्रोफाइल तक पहुंच रहे हैं...",
    // Pricing
    price_title: "अधिग्रहण स्तर",
    price_subtitle: "गहन क्षेत्रीय विश्लेषण, प्रतिस्पर्धी ट्रैकिंग और उन्नत एआई अंतर्दृष्टि तक पूर्ण पहुंच अनलॉक करें।",
    price_starter: "स्टार्टर प्रोटोकॉल",
    price_starter_desc: "आकस्मिक विचारों की खोज करने वाले व्यक्तियों के लिए बिल्कुल सही।",
    price_pro: "अभिजात वर्ग पेशेवर",
    price_pro_desc: "गंभीर उद्यमियों और एजेंसियों के लिए।",
    price_free: "मुफ्त पहुंच शुरू करें",
    price_upgrade: "अभिजात वर्ग में अपग्रेड करें",
    price_popular: "सबसे इष्टतम",
    price_searches: "क्षेत्रीय खोजें",
    price_unlimited: "असीमित खोजें",
    price_google: "बुनियादी वेब रुझान",
    price_adv_data: "उन्नत डेटा मानचित्रण",
    price_recs: "खुफिया रिपोर्ट",
    price_sent: "भावना विश्लेषण",
    price_comp: "क्षेत्रीय मानचित्रण",
    price_export: "निर्देश निर्यात करें"
  },
  Spanish: {
    // Navbar
    nav_dashboard: "Terminal",
    nav_profile: "Perfil de Usuario",
    nav_logout: "Terminar Sesión",
    nav_select_lang: "Seleccionar Idioma de Inteligencia",
    // Home Page
    hero_badge: "Protocolo Avanzado de Inteligencia Neural",
    hero_title_1: "Despliegue Rentabilidad en",
    hero_title_2: "Cualquier Territorio",
    hero_subtitle: "Utilizando escaneos neurales en tiempo real de tendencias globales y sentimiento comunitario para diseñar empresas de alto crecimiento.",
    btn_start_scan: "Iniciar Escaneo de Mercado",
    btn_pricing: "Niveles de Adquisición",
    feat_title: "Marco de Inteligencia Estratégica",
    feat_subtitle: "Agregando puntos de datos multivectoriales para sintetizar planos de despliegue accionables.",
    feat_1_title: "Mapeo Territorial",
    feat_1_desc: "Defina su objetivo geográfico. Nuestros sistemas mapean la densidad demográfica y las huellas digitales localizadas.",
    feat_2_title: "Extracción de Sentimiento",
    feat_2_desc: "Análisis neural de las redes comunitarias para identificar la fricción y la demanda del mercado no vocalizadas.",
    feat_3_title: "Síntesis de Directivas",
    feat_3_desc: "Planes operativos generados que detallan la asignación de capital, la evaluación de riesgos y las secuencias de lanzamiento.",
    banner_title: "¿Listo para Diseñar su Empresa?",
    banner_desc: "Únase a emprendedores globales que utilizan inteligencia localizada para mitigar los riesgos de entrada al mercado.",
    banner_btn: "Activar Acceso a la Terminal",
    // Dashboard
    dash_market_scope: "Perímetro Geográfico",
    dash_target_loc: "Dominio Objetivo",
    dash_enter_city: "Especifique ciudad, distrito o región...",
    dash_analyze: "Ejecutar Escaneo Neural",
    dash_analyzing: "Descifrando Señales Regionales...",
    dash_ai_insights: "Vectores de Inteligencia",
    dash_ai_desc: "Nuestra arquitectura neural cruza el sentimiento comunitario en tiempo real con indicadores económicos globales.",
    dash_vector_global: "Análisis Vectorial en Tiempo Real",
    dash_vector_predict: "Motor Económico Predictivo",
    dash_results_header: "Informe de Inteligencia:",
    dash_strategic_opps: "Oportunidades Estratégicas Identificadas",
    dash_view_plan: "Acceder al Plan de Despliegue",
    dash_match_score: "Ajuste de Sinergia",
    dash_revenue: "Ingresos Proyectados",
    dash_capital: "Capital Inicial",
    dash_prob: "Probabilidad de Supervivencia",
    dash_neural_input: "Verificación de Fuente Neural",
    dash_source_web: "Indicadores de Tendencias Globales (Google)",
    dash_source_reddit: "Sentimiento Comunitario (Reddit)",
    dash_empty_title: "Terminal Lista para Entrada",
    dash_empty_desc: "Esperando coordenadas territoriales para iniciar la secuencia de inteligencia de mercado profunda.",
    // Roadmap
    road_return: "Regresar a la Terminal",
    road_directive: "Directiva Operativa",
    road_milestones: "Secuencia de Hitos",
    road_timeline: "Cronograma Estratégico",
    road_team: "Asignación de Recursos",
    road_phase: "FASE",
    road_priority: "Misión Crítica",
    road_action: "Protocolo Requerido",
    road_readiness: "Preparación Confirmada",
    road_confirmed_desc: "El plan de despliegue ha sido optimizado para el terreno económico identificado. Ejecución autorizada.",
    road_print: "Generar Documento de Protocolo",
    // Profile
    prof_header: "Configuración de Usuario",
    prof_email_label: "Cuenta de Correo Autorizada",
    prof_name: "Nombre Legal Completo",
    prof_bio: "Biografía Profesional",
    prof_phone: "Número de Contacto Táctico",
    prof_save: "Sincronizar Cambios",
    prof_updated: "Configuración Sincronizada Exitosamente",
    prof_placeholder_name: "Ingrese nombre completo...",
    prof_placeholder_bio: "Describa sus objetivos profesionales...",
    prof_placeholder_phone: "Ingrese dígitos de contacto...",
    prof_loading: "Accediendo al Perfil Seguro...",
    // Pricing
    price_title: "Niveles de Adquisición",
    price_subtitle: "Desbloquee el acceso total a análisis regionales profundos, seguimiento de competidores y conocimientos avanzados de IA.",
    price_starter: "Protocolo Inicial",
    price_starter_desc: "Perfecto para individuos que exploran ideas casuales.",
    price_pro: "Profesional de Élite",
    price_pro_desc: "Para emprendedores y agencias serias.",
    price_free: "Iniciar Acceso Gratuito",
    price_upgrade: "Actualizar a Élite",
    price_popular: "MÁS ÓPTIMO",
    price_searches: "Búsquedas Regionales",
    price_unlimited: "Búsquedas Ilimitadas",
    price_google: "Tendencias Web Básicas",
    price_adv_data: "Mapeo de Datos Avanzado",
    price_recs: "Informes de Inteligencia",
    price_sent: "Análisis de Sentimiento",
    price_comp: "Mapeo Territorial",
    price_export: "Exportar Directivas"
  },
  French: {
    // Navbar
    nav_dashboard: "Terminal",
    nav_profile: "Profil Utilisateur",
    nav_logout: "Terminer la Session",
    nav_select_lang: "Sélectionner la Langue d'Intelligence",
    // Home Page
    hero_badge: "Protocole d'Intelligence Neurale Avancé",
    hero_title_1: "Déployez la Rentabilité dans",
    hero_title_2: "N'importe quel Territoire",
    hero_subtitle: "Utilisation de scanners neuraux en temps réel des tendances mondiales et du sentiment de la communauté pour concevoir des entreprises à forte croissance.",
    btn_start_scan: "Initier le Scan du Marché",
    btn_pricing: "Niveaux d'Acquisition",
    feat_title: "Cadre d'Intelligence Stratégique",
    feat_subtitle: "Agrégation de points de données multi-vectoriels pour synthétiser des plans de déploiement exploitables.",
    feat_1_title: "Cartographie Territoriale",
    feat_1_desc: "Définissez votre cible géographique. Nos systèmes cartographient la densité démographique et les empreintes numériques localisées.",
    feat_2_title: "Extraction de Sentiment",
    feat_2_desc: "Analyse neurale des réseaux communautaires pour identifier les frictions et la demande du marché non vocalisées.",
    feat_3_title: "Synthèse de Directives",
    feat_3_desc: "Plans opérationnels générés détaillant l'allocation de capital, l'évaluation des risques et les séquences de lancement.",
    banner_title: "Prêt à Concevoir votre Entreprise ?",
    banner_desc: "Rejoignez les entrepreneurs mondiaux utilisant l'intelligence localisée pour atténuer les risques d'entrée sur le marché.",
    banner_btn: "Activer l'Accès au Terminal",
    // Dashboard
    dash_market_scope: "Périmètre Géographique",
    dash_target_loc: "Domaine Cible",
    dash_enter_city: "Spécifiez la ville, le district ou la région...",
    dash_analyze: "Exécuter le Scan Neural",
    dash_analyzing: "Décryptage des Signaux Régionaux...",
    dash_ai_insights: "Vecteurs d'Intelligence",
    dash_ai_desc: "Notre architecture neurale croise le sentiment de la communauté en temps réel avec les indicateurs économiques mondiaux.",
    dash_vector_global: "Analyse Vectorielle en Temps Réel",
    dash_vector_predict: "Moteur Économique Prédictif",
    dash_results_header: "Rapport d'Intelligence :",
    dash_strategic_opps: "Opportunités Stratégiques Identifiées",
    dash_view_plan: "Accéder au Plan de Déploiement",
    dash_match_score: "Match de Synergie",
    dash_revenue: "Revenu Projeté",
    dash_capital: "Capital Initial",
    dash_prob: "Probabilité de Survie",
    dash_neural_input: "Vérification de la Source Neurale",
    dash_source_web: "Indicateurs de Tendances Mondiales (Google)",
    dash_source_reddit: "Sentiment de la Communauté (Reddit)",
    dash_empty_title: "Terminal Prêt pour l'Entrée",
    dash_empty_desc: "En attente de coordonnées territoriales pour initier la séquence d'intelligence de marché profonde.",
    // Roadmap
    road_return: "Retour au Terminal",
    road_directive: "Directive Opérationnelle",
    road_milestones: "Séquence de Jalons",
    road_timeline: "Calendrier Stratégique",
    road_team: "Allocation des Ressources",
    road_phase: "PHASE",
    road_priority: "Mission Critique",
    road_action: "Protocole Requis",
    road_readiness: "Préparation Confirmée",
    road_confirmed_desc: "Le plan de déploiement a été optimisé pour le terrain économique identifié. Exécution autorisée.",
    road_print: "Générer le Document de Protocole",
    // Profile
    prof_header: "Configuration Utilisateur",
    prof_email_label: "Compte Email Autorisé",
    prof_name: "Nom Légal Complet",
    prof_bio: "Biographie Professionnelle",
    prof_phone: "Numéro de Contact Tactique",
    prof_save: "Synchroniser les Changements",
    prof_updated: "Configuration Synchronisée avec Succès",
    prof_placeholder_name: "Entrez le nom complet...",
    prof_placeholder_bio: "Décrivez vos objectifs professionnels...",
    prof_placeholder_phone: "Entrez les chiffres de contact...",
    prof_loading: "Accès au Profil Sécurisé...",
    // Pricing
    price_title: "Niveaux d'Acquisition",
    price_subtitle: "Débloquez un accès complet aux analyses régionales approfondies, au suivi des concurrents et aux informations IA avancées.",
    price_starter: "Protocole de Départ",
    price_starter_desc: "Parfait pour les individus explorant des idées occasionnelles.",
    price_pro: "Élite Professionnelle",
    price_pro_desc: "Pour les entrepreneurs et agences sérieux.",
    price_free: "Initier l'Accès Gratuit",
    price_upgrade: "Passer à l'Élite",
    price_popular: "LE PLUS OPTIMAL",
    price_searches: "Recherches Régionales",
    price_unlimited: "Recherches Illimitées",
    price_google: "Tendances Web de Base",
    price_adv_data: "Cartographie de Données Avancée",
    price_recs: "Rapports d'Intelligence",
    price_sent: "Analyse de Sentiment",
    price_comp: "Cartographie Territoriale",
    price_export: "Exporter les Directives"
  },
  German: {
    // Navbar
    nav_dashboard: "Terminal",
    nav_profile: "Benutzerprofil",
    nav_logout: "Sitzung Beenden",
    nav_select_lang: "Intelligenzsprache Auswählen",
    // Home Page
    hero_badge: "Fortgeschrittenes Neurales Intelligenzprotokoll",
    hero_title_1: "Rentabilität Einsetzen in",
    hero_title_2: "Jedem Territorium",
    hero_subtitle: "Nutzung von Echtzeit-Neuralscans globaler Trends und Community-Sentiment zur Gestaltung wachstumsstarker Geschäftsmodelle.",
    btn_start_scan: "Marktscan Initiieren",
    btn_pricing: "Erwerbsstufen",
    feat_title: "Strategischer Intelligenzrahmen",
    feat_subtitle: "Aggregation von Multi-Vektor-Datenpunkten zur Synthese umsetzbarer Einsatzpläne.",
    feat_1_title: "Territoriale Kartierung",
    feat_1_desc: "Definieren Sie Ihr geografisches Ziel. Unsere Systeme kartieren die demografische Dichte und lokalisierte digitale Fußabdrücke.",
    feat_2_title: "Sentiment-Extraktion",
    feat_2_desc: "Neurale Analyse von Community-Netzwerken zur Identifizierung nicht artikulierter Marktreibungen und Nachfragen.",
    feat_3_title: "Direktiven-Synthese",
    feat_3_desc: "Generierte Betriebspläne mit detaillierter Kapitalallokation, Risikobewertung und Startsequenzen.",
    banner_title: "Bereit, Ihr Unternehmen zu Gestalten?",
    banner_desc: "Schließen Sie sich globalen Unternehmern an, die lokalisierte Intelligenz nutzen, um Markteintrittsrisiken zu mindern.",
    banner_btn: "Terminalzugang Aktivieren",
    // Dashboard
    dash_market_scope: "Geografischer Perimeter",
    dash_target_loc: "Zielbereich",
    dash_enter_city: "Stadt, Bezirk oder Region angeben...",
    dash_analyze: "Neuralscan Durchführen",
    dash_analyzing: "Regionale Signale Entschlüsseln...",
    dash_ai_insights: "Intelligenzvektoren",
    dash_ai_desc: "Unsere neurale Architektur gleicht Echtzeit-Community-Sentiment mit globalen Wirtschaftsindikatoren ab.",
    dash_vector_global: "Echtzeit-Vektoranalyse",
    dash_vector_predict: "Prädiktive Wirtschaftsmaschine",
    dash_results_header: "Intelligenzbericht:",
    dash_strategic_opps: "Identifizierte Strategische Möglichkeiten",
    dash_view_plan: "Einsatzplan Aufrufen",
    dash_match_score: "Synergie-Match",
    dash_revenue: "Prognostizierter Umsatz",
    dash_capital: "Initialkapital",
    dash_prob: "Überlebenswahrscheinlichkeit",
    dash_neural_input: "Neurale Quellenverifizierung",
    dash_source_web: "Globale Trendindikatoren (Google)",
    dash_source_reddit: "Community-Sentiment (Reddit)",
    dash_empty_title: "Terminal Bereit für Eingabe",
    dash_empty_desc: "Warten auf territoriale Koordinaten, um die Sequenz für tiefe Marktintelligenz zu starten.",
    // Roadmap
    road_return: "Zurück zum Terminal",
    road_directive: "Operative Direktive",
    road_milestones: "Meilenstein-Sequenz",
    road_timeline: "Strategischer Zeitplan",
    road_team: "Ressourcenallokation",
    road_phase: "PHASE",
    road_priority: "Missionskritisch",
    road_action: "Erforderliches Protokoll",
    road_readiness: "Bereitschaft Bestätigt",
    road_confirmed_desc: "Der Einsatzplan wurde für das identifizierte wirtschaftliche Terrain optimiert. Ausführung ist autorisiert.",
    road_print: "Protokolldokument Generieren",
    // Profile
    prof_header: "Benutzerkonfiguration",
    prof_email_label: "Autorisiertes E-Mail-Konto",
    prof_name: "Gesetzlicher Vollständiger Name",
    prof_bio: "Professionelle Biografie",
    prof_phone: "Taktische Kontaktnummer",
    prof_save: "Änderungen Synchronisieren",
    prof_updated: "Konfiguration Erfolgreich Synchronisiert",
    prof_placeholder_name: "Vollständigen Namen eingeben...",
    prof_placeholder_bio: "Beschreiben Sie Ihre beruflichen Ziele...",
    prof_placeholder_phone: "Kontaktnummer eingeben...",
    prof_loading: "Zugriff auf Sicheres Profil...",
    // Pricing
    price_title: "Erwerbsstufen",
    price_subtitle: "Schalten Sie den vollen Zugriff auf tiefe regionale Analysen, Wettbewerber-Tracking und fortgeschrittene KI-Einblicke frei.",
    price_starter: "Starter-Protokoll",
    price_starter_desc: "Perfekt für Einzelpersonen, die gelegentliche Ideen erkunden.",
    price_pro: "Elite-Profi",
    price_pro_desc: "Für ernsthafte Unternehmer und Agenturen.",
    price_free: "Kostenlosen Zugang Initiieren",
    price_upgrade: "Auf Elite Upgraden",
    price_popular: "AM OPTIMALSTEN",
    price_searches: "Regionale Suchen",
    price_unlimited: "Unbegrenzte Suchen",
    price_google: "Basis-Webtrends",
    price_adv_data: "Fortgeschrittene Datenkartierung",
    price_recs: "Intelligenzberichte",
    price_sent: "Sentiment-Analyse",
    price_comp: "Territoriale Kartierung",
    price_export: "Direktiven Exportieren"
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState("English");

  // Load language from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem("app_lang");
    if (saved && translations[saved]) {
      setLanguage(saved);
    }
  }, []);

  // Save language to localStorage on change
  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
